// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Odontosoft.Backend.Data;

#nullable disable

namespace Odontosoft.Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251208200531_initialDB")]
    partial class initialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Odontosoft.Shared.Entities.Clinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clinicas");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Diagnostico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoICD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosticoDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpedienteClinicoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteClinicoId");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Evolucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpedienteClinicoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteClinicoId");

                    b.ToTable("Evoluciones");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.ExpedienteClinico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.HasIndex("SucursalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ExpedientesClinicos");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.FirmaDigital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpedienteClinicoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteClinicoId");

                    b.ToTable("FirmasDigitales");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.FotografiaIntraoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpedienteClinicoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteClinicoId");

                    b.ToTable("FotografiasIntraorales");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.NotaClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpedienteClinicoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteClinicoId");

                    b.ToTable("NotasClinicas");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaNacimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Prescripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpedienteClinicoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instrucciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteClinicoId");

                    b.ToTable("Prescripciones");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Radiografia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpedienteClinicoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteClinicoId");

                    b.ToTable("Radiografias");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicaId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Horarios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Tratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpedienteClinicoId")
                        .HasColumnType("int");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteClinicoId");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.UsuarioSucursal", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "SucursalId");

                    b.HasIndex("SucursalId");

                    b.ToTable("UsuarioSucursales");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Diagnostico", b =>
                {
                    b.HasOne("Odontosoft.Shared.Entities.ExpedienteClinico", "ExpedienteClinico")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("ExpedienteClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpedienteClinico");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Evolucion", b =>
                {
                    b.HasOne("Odontosoft.Shared.Entities.ExpedienteClinico", "ExpedienteClinico")
                        .WithMany("Evoluciones")
                        .HasForeignKey("ExpedienteClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpedienteClinico");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.ExpedienteClinico", b =>
                {
                    b.HasOne("Odontosoft.Shared.Entities.Paciente", "Paciente")
                        .WithOne("ExpedienteClinico")
                        .HasForeignKey("Odontosoft.Shared.Entities.ExpedienteClinico", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Odontosoft.Shared.Entities.Sucursal", "Sucursal")
                        .WithMany("ExpedientesClinicos")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Odontosoft.Shared.Entities.Usuario", null)
                        .WithMany("ExpedientesClinicos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Paciente");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.FirmaDigital", b =>
                {
                    b.HasOne("Odontosoft.Shared.Entities.ExpedienteClinico", "ExpedienteClinico")
                        .WithMany("FirmasDigitales")
                        .HasForeignKey("ExpedienteClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpedienteClinico");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.FotografiaIntraoral", b =>
                {
                    b.HasOne("Odontosoft.Shared.Entities.ExpedienteClinico", "ExpedienteClinico")
                        .WithMany("FotografiasIntraorales")
                        .HasForeignKey("ExpedienteClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpedienteClinico");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.NotaClinica", b =>
                {
                    b.HasOne("Odontosoft.Shared.Entities.ExpedienteClinico", "ExpedienteClinico")
                        .WithMany("NotasClinicas")
                        .HasForeignKey("ExpedienteClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpedienteClinico");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Prescripcion", b =>
                {
                    b.HasOne("Odontosoft.Shared.Entities.ExpedienteClinico", "ExpedienteClinico")
                        .WithMany("Prescripciones")
                        .HasForeignKey("ExpedienteClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpedienteClinico");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Radiografia", b =>
                {
                    b.HasOne("Odontosoft.Shared.Entities.ExpedienteClinico", "ExpedienteClinico")
                        .WithMany("Radiografias")
                        .HasForeignKey("ExpedienteClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpedienteClinico");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Sucursal", b =>
                {
                    b.HasOne("Odontosoft.Shared.Entities.Clinica", "Clinica")
                        .WithMany("Sucursales")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Tratamiento", b =>
                {
                    b.HasOne("Odontosoft.Shared.Entities.ExpedienteClinico", "ExpedienteClinico")
                        .WithMany("Tratamientos")
                        .HasForeignKey("ExpedienteClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpedienteClinico");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.UsuarioSucursal", b =>
                {
                    b.HasOne("Odontosoft.Shared.Entities.Sucursal", "Sucursal")
                        .WithMany("UsuarioSucursales")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Odontosoft.Shared.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioSucursales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Clinica", b =>
                {
                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.ExpedienteClinico", b =>
                {
                    b.Navigation("Diagnosticos");

                    b.Navigation("Evoluciones");

                    b.Navigation("FirmasDigitales");

                    b.Navigation("FotografiasIntraorales");

                    b.Navigation("NotasClinicas");

                    b.Navigation("Prescripciones");

                    b.Navigation("Radiografias");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Paciente", b =>
                {
                    b.Navigation("ExpedienteClinico")
                        .IsRequired();
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Sucursal", b =>
                {
                    b.Navigation("ExpedientesClinicos");

                    b.Navigation("UsuarioSucursales");
                });

            modelBuilder.Entity("Odontosoft.Shared.Entities.Usuario", b =>
                {
                    b.Navigation("ExpedientesClinicos");

                    b.Navigation("UsuarioSucursales");
                });
#pragma warning restore 612, 618
        }
    }
}
